version: "2"
services:
  nodejs:
    container_name: dashboard
    build: .
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ".:/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app/src
    command: bash -c "npm install && npm run start"
