version: "3.5"
services:
  nodejs:
    container_name: dashboard
    build: nodejs/
    restart: unless-stopped
    networks:
      - dockOS
    ports:
      - "8888:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "./media:/media"
    working_dir: /app/nodejs
    command: node index.js
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ".:/app"
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    depends_on:
      - nodejs
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  dockOS:
    name: dockOS
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
