version: "3.5"
services:
  nodejs:
    container_name: dashboard
    build: .
    restart: unless-stopped
    networks:
      - dockEμ
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ".:/app"
      - "./media:/media"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app/src
    command: node index.js

networks:
  dockEμ:
    name: dockEμ
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
