version: "2"
services:
  nodejs:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ".:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: /app/dashboard
    command: nodejs index.js
  filebrowser:
    image: "filebrowser/filebrowser"
    restart: unless-stopped
    user: "${UID}:${GID}"
    entrypoint: /filebrowser
    command: --port 80 --database /data/database.db --root /srv
    ports:
      - "8000:80"
    volumes:
      - "filebrowser:/data"
      - "./media:/srv"
  minidlna:
    image: "vladgh/minidlna"
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "8200:8200/tcp"
      - "1900:1900/udp"
    volumes:
      - "./media:/media"
    environment:
      MINIDLNA_MEDIA_DIR: /media
      MINIDLNA_FRIENDLY_NAME: custom-nas
      MINIDLNA_INOTIFY: "no"

volumes:
    filebrowser:
        external: false
