version: "2"
services:
  nodejs:
    container_name: dashboard
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ".:/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app/src
    command: node index.js
